apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- base/argocd-alb-service.yaml
- base/argo-cd-ui-ingress.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml

patchesStrategicMerge:
# - overlays/production/argocd-cmd-params-cm.yaml
- overlays/production/argocd-server-service.yaml

images:
- name: quay.io/argoproj/argocd
  newName: ghcr.io/argoproj/argo-cd/argocd
  newTag: 2.9.0-d2720732
